<?php

return [
    'delhi-food-trail' => [
        'title' => 'A plate-by-plate guide to Delhi',
        'category' => 'Food & culture',
        'location' => 'Delhi, India',
        'read_time' => '6 min read',
        'date' => '12 September 2024',
        'image' => 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=1400&q=85',
        'intro' => 'Delhi is best understood one bite at a time. Follow the smoke, the spice, and the stories around every shared table.',
        'body' => [
            'Start early in Old Delhi, when the lanes are still cool and the first kettles of chai are beginning to sing. The city wakes in layers: bread in the tandoor, cardamom in the air, and a thousand small conversations spilling into the street.',
            'By afternoon, make room for a slower meal. Delhi rewards curiosity, so leave the itinerary loose enough for a shopkeeper’s recommendation or a turn down a lane you did not plan to take.',
        ],
    ],

    'agra-beyond-taj' => [
        'title' => 'Agra beyond the Taj Mahal',
        'category' => 'Heritage',
        'location' => 'Agra, Uttar Pradesh',
        'read_time' => '5 min read',
        'date' => '04 September 2024',
        'image' => 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1400&q=85',
        'intro' => 'The Taj is only the beginning. Spend a little longer in Agra and the city reveals a quieter, more textured kind of wonder.',
        'body' => [
            'Arrive before sunrise and let the marble change colour in front of you. Then take the long way back through the old city, where inlay artists and generations of storytellers keep the Mughal chapter alive.',
            'At dusk, cross the river to Mehtab Bagh. The view is familiar, but the silence on the opposite bank makes it feel entirely new.',
        ],
    ],

    'kashmir-slow-travel' => [
        'title' => 'The gentle art of slowing down in Kashmir',
        'category' => 'Mountains & wild',
        'location' => 'Jammu & Kashmir, India',
        'read_time' => '7 min read',
        'date' => '28 August 2024',
        'image' => 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1400&q=85',
        'intro' => 'In Kashmir, the best days are measured in cups of kahwa, lake light, and the distance between one beautiful view and the next.',
        'body' => [
            'Choose a houseboat with a view of the waking lake. There is no need to rush the morning; the mountains will still be there after breakfast, and the shikara ride is better when the water is quiet.',
            'Leave space for the weather to change your plans. A soft rain on cedar roofs, a shared lunch, or a sudden patch of clear sky can become the most memorable part of the route.',
        ],
    ],

    'himachal-cafe-trail' => [
        'title' => 'A café trail through the Himachal hills',
        'category' => 'Slow travel',
        'location' => 'Himachal Pradesh, India',
        'read_time' => '4 min read',
        'date' => '16 August 2024',
        'image' => 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1400&q=85',
        'intro' => 'Trade traffic for pine trails and find the small cafés that make Himachal feel like a place you could stay forever.',
        'body' => [
            'The best Himachal cafés are often found at the end of a walk. Follow the scent of fresh bread, sit near a window, and let a local playlist become the soundtrack to an unplanned afternoon.',
            'Between stops, take the forest roads slowly. This is a landscape that gives more back when you stop trying to see it all at once.',
        ],
    ],

    'who-is-nirmal-purja-nimsdai' => [
        'title' => 'Nirmal Purja: the impossible made possible',
        'category' => 'People & adventure',
        'location' => 'The Himalayas, Nepal',
        'read_time' => '7 min read',
        'date' => '15 September 2024',
        'image' => asset('images/nirmal.jpg'),
        'intro' => 'Known as Nims or Nimsdai, Nirmal Purja has changed the way the world talks about high-altitude adventure, courage, and possibility.',
        'keywords' => 'Nirmal Purja, Nims, Nimsdai, Project Possible, 14 Peaks, Himalayan mountaineering',
        'sections' => [
            ['heading' => 'Who is Nirmal Purja?', 'paragraphs' => ['Nirmal Purja, widely known as Nims or Nimsdai, is a Nepali-British mountaineer whose record-setting climbs have brought a new level of attention to Himalayan expedition culture. His work combines elite physical ability with a disciplined approach to logistics, teamwork, and risk.']],
            ['heading' => 'Project Possible and the 14 Peaks', 'paragraphs' => ['Nimsdai became internationally known through Project Possible, his extraordinary attempt to climb all fourteen of the world’s 8,000-metre peaks. He completed the challenge in six months and six days in 2019, a feat that reshaped expectations in Himalayan mountaineering.', 'His story is not only about speed or summit photographs. It is about preparation, teamwork, resilience, and a refusal to accept that a path is impossible simply because it has not been taken before.']],
            ['heading' => 'From the Gurkhas to the high Himalaya', 'paragraphs' => ['Before becoming a full-time climber, Purja served with the Brigade of Gurkhas and the British military’s Special Boat Service. That experience shaped the expedition habits people often associate with him: clear roles, calm decisions under pressure, and trust built long before the summit push.', 'His journey reached a wider audience through the documentary 14 Peaks: Nothing Is Impossible. But beyond the records and the film, the lasting story is collective. High-altitude achievements depend on Sherpa partners, logistics teams, families, and weather windows.']],
            ['heading' => 'What travellers can learn from Nimsdai', 'paragraphs' => ['The mountains demand respect at every altitude. Whether you are planning a serious expedition or simply taking your first high-country walk, the Nimsdai mindset begins with discipline, good local guidance, and knowing when the mountain is asking you to wait.']],
        ],
    ],

    'places-to-visit-in-rajasthan' => [
        'title' => 'Places to Visit in Rajasthan: 15 Best Destinations for an Unforgettable Trip',
        'category' => 'Travel & heritage',
        'location' => 'Rajasthan, India',
        'read_time' => '18 min read',
        'date' => '23 September 2026',
        'image' => 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1400&q=85',
        'intro' => 'Rajasthan is a land of grand forts, magnificent palaces, colourful markets, ancient temples, desert landscapes, peaceful lakes and rich cultural traditions. From the historic streets of Jaipur and the blue houses of Jodhpur to the golden sands of Jaisalmer and the lakes of Udaipur, Rajasthan offers a remarkable variety of experiences for travellers.',
        'body' => [
            'Whether you are planning a family holiday, a romantic trip, a cultural journey, a wildlife adventure or a Rajasthan road trip, there are plenty of places to explore across the state.',
            'The state is home to some of India\'s most recognisable heritage destinations, while smaller towns such as Bundi, Pushkar, Mandawa and Mount Abu offer a different pace and atmosphere. Rajasthan Tourism also highlights destinations ranging from Jaipur, Udaipur, Jodhpur and Jaisalmer to Ranthambore, Pushkar, Bundi, Bikaner, Bharatpur and Mount Abu.',
            'If you are wondering where to go in Rajasthan, this guide covers some of the best places to visit and what makes each destination worth adding to your itinerary.',
            '1. Jaipur – The Pink City',
            'Jaipur is one of the most popular places to visit in Rajasthan and an excellent starting point for exploring the state.',
            'Known as the Pink City, Jaipur combines historic architecture with busy markets, traditional crafts, restaurants and modern city life. The city was founded in 1727 by Maharaja Sawai Jai Singh II and is recognised by Rajasthan Tourism for its planned urban design and distinctive pink-coloured architecture.',
            ['type' => 'list', 'heading' => 'Places to visit in Jaipur', 'items' => ['Amber Fort', 'Hawa Mahal', 'City Palace', 'Jantar Mantar', 'Nahargarh Fort', 'Jaigarh Fort', 'Jal Mahal', 'Albert Hall Museum']],
            'Amber Fort is particularly popular for its impressive architecture and hilltop setting, while Hawa Mahal has become one of the most recognisable landmarks associated with Jaipur.',
            'The city\'s markets are also worth exploring if you are interested in jewellery, textiles, handicrafts and traditional Rajasthani products.',
            'How many days are enough for Jaipur? Around 2 to 3 days can give you enough time to explore the major attractions without rushing.',
            '2. Udaipur – The City of Lakes',
            'Udaipur is known for its lakes, palaces and scenic surroundings. The city was founded in 1553 by Maharana Udai Singh II as the capital of the Mewar Kingdom.',
            'The combination of Lake Pichola, historic palaces and the surrounding Aravalli hills gives Udaipur a distinctly different atmosphere from Rajasthan\'s desert cities.',
            ['type' => 'list', 'heading' => 'Places to visit in Udaipur', 'items' => ['City Palace', 'Lake Pichola', 'Lake Palace', 'Sajjangarh Monsoon Palace', 'Fateh Sagar Lake', 'Jagdish Temple', 'Saheliyon-ki-Bari', 'Bagore Ki Haveli']],
            'A boat ride on Lake Pichola is a popular way to experience the city\'s lakeside architecture, particularly around sunset.',
            'Udaipur is also a good choice for travellers looking for a slower holiday with scenic views, heritage hotels, lakeside walks and cultural experiences.',
            '3. Jodhpur – The Blue City',
            'Jodhpur is another major destination on a Rajasthan itinerary. Often called the Blue City because of the blue-painted houses around the old city, Jodhpur is dominated by the impressive Mehrangarh Fort.',
            'Rajasthan Tourism describes Jodhpur as a blend of modern and traditional life and highlights its historically important landmarks.',
            ['type' => 'list', 'heading' => 'Places to visit in Jodhpur', 'items' => ['Mehrangarh Fort', 'Jaswant Thada', 'Umaid Bhawan Palace', 'Mandore Gardens', 'Clock Tower and Sardar Market', 'Toorji Ka Jhalra']],
            'Mehrangarh Fort is the city\'s major landmark and offers impressive views across the surrounding urban landscape.',
            'Spend some time walking through the old city and exploring its markets for handicrafts, textiles, spices and local food.',
            '4. Jaisalmer – The Golden City',
            'If you want to experience Rajasthan\'s desert landscape, Jaisalmer should be high on your itinerary.',
            'Located in the Thar Desert, Jaisalmer is famous for its golden sandstone architecture and the historic Jaisalmer Fort. Rajasthan Tourism describes it as the gateway to the Thar Desert and highlights the fort as one of India\'s famous living forts.',
            ['type' => 'list', 'heading' => 'Places to visit in Jaisalmer', 'items' => ['Jaisalmer Fort', 'Patwon Ki Haveli', 'Salim Singh Ki Haveli', 'Gadisar Lake', 'Bada Bagh', 'Kuldhara', 'Sam Sand Dunes']],
            'One of the highlights of visiting Jaisalmer is spending an evening in the desert. Depending on your itinerary, you can experience a camel safari, cultural performances and an overnight desert camp.',
            'The sandstone buildings become especially striking around sunrise and sunset.',
            '5. Pushkar – A Spiritual and Cultural Destination',
            'Pushkar is one of Rajasthan\'s most distinctive towns. Located near Ajmer, it is known for Pushkar Lake, temples, ghats and its cultural atmosphere.',
            'Rajasthan Tourism identifies Pushkar as one of India\'s oldest cities and notes its religious significance, including the Brahma Temple and Pushkar Lake.',
            ['type' => 'list', 'heading' => 'Places to visit in Pushkar', 'items' => ['Pushkar Lake', 'Brahma Temple', 'Savitri Mata Temple', 'Pushkar Ghats', 'Pushkar Bazaar', 'Nag Pahar']],
            'Pushkar is also associated with its famous annual camel and livestock fair, which attracts visitors interested in its cultural traditions.',
            'For travellers, Pushkar works well as a short stay or as part of a Jaipur-Ajmer-Pushkar itinerary.',
            '6. Ranthambore – For Wildlife and Safaris',
            'Ranthambore offers a completely different experience from Rajasthan\'s historic cities.',
            'Located around Sawai Madhopur, Ranthambore is known for its national park and tiger reserve. The area combines dry deciduous forests, lakes, hills and historic ruins.',
            ['type' => 'list', 'heading' => 'Things to do in Ranthambore', 'items' => ['Go on a wildlife safari', 'explore Ranthambore Fort', 'look for native bird species', 'explore the surrounding natural landscape']],
            'The national park is known for its tiger population, but wildlife sightings are never guaranteed. Visitors can also encounter animals such as leopard, sloth bear, sambar, chital and nilgai.',
            'If you enjoy wildlife photography or nature travel, consider adding Ranthambore to your Rajasthan itinerary.',
            '7. Bikaner – The Desert Heritage City',
            'Bikaner is another fascinating destination in Rajasthan\'s desert region.',
            'The city is known for its forts, palaces, havelis and traditional food. Rajasthan Tourism also highlights Bikaner as a destination associated with camel culture.',
            ['type' => 'list', 'heading' => 'Places to visit in Bikaner', 'items' => ['Junagarh Fort', 'Lalgarh Palace', 'Rampuria Havelis', 'Karni Mata Temple', 'National Research Centre on Camel']],
            'Bikaner is a good option for travellers who want to explore Rajasthan beyond the more frequently visited Jaipur, Jodhpur and Udaipur circuit.',
            '8. Mount Abu – Rajasthan\'s Hill Station',
            'Mount Abu provides a completely different landscape from much of Rajasthan.',
            'Located in the Aravalli Range, Mount Abu is Rajasthan\'s only hill station. It is surrounded by green hills and is known for its lakes, viewpoints, temples and cooler climate.',
            ['type' => 'list', 'heading' => 'Places to visit in Mount Abu', 'items' => ['Nakki Lake', 'Dilwara Jain Temples', 'Guru Shikhar', 'Sunset Point', 'Achalgarh Fort', 'Toad Rock']],
            'Mount Abu can be particularly appealing if you want a break from Rajasthan\'s hotter desert and plains regions.',
            '9. Chittorgarh – A City of Forts and History',
            'Chittorgarh is an important destination for travellers interested in Rajasthan\'s history and architecture.',
            'The city\'s most famous landmark is Chittorgarh Fort, an enormous historic fort complex associated with the history of Mewar.',
            ['type' => 'list', 'heading' => 'Places to visit in Chittorgarh', 'items' => ['Chittorgarh Fort', 'Vijay Stambh', 'Kirti Stambh', 'Rana Kumbha Palace', 'Meera Temple', 'Padmini Palace']],
            'Rajasthan Tourism describes Chittorgarh as a city defined by its imposing fort and its association with Rajput history.',
            '10. Bundi – A Quiet Heritage Escape',
            'Bundi is ideal for travellers looking for a quieter destination.',
            'The town is known for its forts, palaces, stepwells and distinctive architecture. Rajasthan Tourism describes Bundi as a town dotted with palaces and forts and known for its stepwells.',
            ['type' => 'list', 'heading' => 'Places to visit in Bundi', 'items' => ['Taragarh Fort', 'Bundi Palace', 'Chitrashala', 'Raniji Ki Baori', 'Nawal Sagar Lake']],
            'Compared with Jaipur or Udaipur, Bundi generally offers a slower experience and is particularly interesting for photographers and heritage enthusiasts.',
            '11. Ajmer – A Major Pilgrimage Destination',
            'Ajmer is an important religious and historical destination in Rajasthan.',
            'The city is particularly known for the Ajmer Sharif Dargah and its connection with the nearby town of Pushkar.',
            ['type' => 'list', 'heading' => 'Places to visit in Ajmer', 'items' => ['Ajmer Sharif Dargah', 'Ana Sagar Lake', 'Adhai Din Ka Jhonpra', 'Akbari Fort and Museum', 'Taragarh Fort']],
            'Ajmer and Pushkar can easily be combined into one trip because of their proximity.',
            '12. Bharatpur – For Birds and Nature',
            'Bharatpur is located in eastern Rajasthan and is particularly known for Keoladeo National Park.',
            'The destination provides an alternative to Rajasthan\'s forts and palaces, making it a good addition for travellers interested in birds and nature.',
            ['type' => 'list', 'heading' => 'Places to visit in Bharatpur', 'items' => ['Keoladeo National Park', 'Bharatpur Palace', 'Lohagarh Fort', 'Government Museum']],
            'The combination of Bharatpur with Agra can also work well for travellers exploring the Golden Triangle region.',
            '13. Alwar – Forts, Lakes and Nature',
            'Alwar is another destination worth considering if you want to explore Rajasthan beyond its most famous cities.',
            'The city and surrounding region offer forts, palaces, lakes and natural landscapes.',
            ['type' => 'list', 'heading' => 'Places to visit in Alwar', 'items' => ['Bala Quila', 'City Palace', 'Siliserh Lake', 'Sariska Tiger Reserve', 'Moosi Maharani Ki Chhatri']],
            'Its location also makes Alwar useful for travellers coming from Delhi and the NCR region.',
            '14. Mandawa – Explore the Havelis of Shekhawati',
            'Mandawa is located in the Shekhawati region and is known for its beautifully decorated havelis and frescoes.',
            'The town provides a glimpse into a different side of Rajasthan\'s architectural heritage.',
            ['type' => 'list', 'heading' => 'Things to see in Mandawa', 'items' => ['Mandawa Fort', 'historic havelis', 'fresco paintings', 'traditional streets and markets']],
            'For travellers interested in architecture and photography, Mandawa can be a rewarding stop on a Rajasthan road trip.',
            '15. Kumbhalgarh – A Fort in the Aravallis',
            'Kumbhalgarh is known for its massive fortification and location in the Aravalli hills.',
            'The destination is particularly suitable for travellers interested in forts, history and mountain landscapes.',
            'Kumbhalgarh can also be combined with Udaipur and nearby destinations when planning a southern Rajasthan itinerary.',
            'Which Places Should You Visit in Rajasthan?',
            'The answer depends on the kind of experience you want.',
            'For history and forts, consider: Jaipur, Jodhpur, Chittorgarh, Kumbhalgarh, Jaisalmer, Bundi.',
            'For lakes and romantic getaways, consider: Udaipur, Mount Abu, Pushkar. Udaipur is particularly known for its lakes and palace architecture.',
            'For desert experiences, consider: Jaisalmer, Bikaner, Jodhpur, Pushkar.',
            'For wildlife, consider: Ranthambore, Bharatpur, Sariska.',
            'For a quieter Rajasthan experience, consider: Bundi, Mandawa, Kumbhalgarh, Alwar, Mount Abu.',
            'Best Time to Visit Rajasthan',
            'The best time for a Rajasthan trip depends on where you are going and what you want to do.',
            'The period from October to March is generally the most comfortable for exploring many parts of Rajasthan because temperatures are more pleasant than during the peak summer months. Rajasthan Tourism notes that summer can be particularly hot, while winter offers more comfortable daytime conditions for sightseeing.',
            'October to March: This is a popular period for sightseeing, sightseeing tours, desert experiences and outdoor activities.',
            'April to June: Summer can be very hot, particularly in desert and inland areas. If travelling during this period, plan outdoor sightseeing carefully and consider destinations such as Mount Abu or higher areas of the Aravallis.',
            'July to September: The monsoon can bring a different character to Rajasthan. Udaipur, Bundi and other destinations can be particularly scenic during this period.',
            'How Many Days Do You Need for a Rajasthan Trip?',
            'For a first Rajasthan trip, 7 to 10 days can provide enough time to experience several major destinations.',
            'A possible itinerary could be a 7-Day Rajasthan Itinerary: Day 1: Jaipur, Day 2: Jaipur, Day 3: Jodhpur, Day 4: Jodhpur, Day 5: Jaisalmer, Day 6: Jaisalmer and desert experience, Day 7: Departure.',
            'For a more relaxed trip, you could extend the journey and add Udaipur, Pushkar or Ranthambore.',
            'Rajasthan Travel Tips',
            'Plan around the weather: Rajasthan can be extremely hot during summer. Check the expected weather for each destination before planning long outdoor sightseeing days.',
            'Keep some flexibility: Travel between Rajasthan\'s cities can take several hours. Avoid filling every day with too many attractions.',
            'Start sightseeing early: Morning hours can be more comfortable, particularly during warmer months.',
            'Carry sun protection: Sunglasses, sunscreen, a hat and comfortable clothing are useful for sightseeing.',
            'Respect local traditions: Rajasthan has many important religious and cultural sites. Dress appropriately and follow photography rules where applicable.',
            'Try local cuisine: Rajasthan is known for dishes such as dal baati churma, gatte ki sabzi, ker sangri, pyaaz kachori and traditional sweets.',
            'Book popular accommodation in advance: Hotels and heritage properties in popular destinations can become busy during peak travel periods.',
            'Final Thoughts',
            'Rajasthan is not a destination that can be fully experienced in just one trip. Its major cities each have a distinct character, from Jaipur\'s historic architecture and Jodhpur\'s blue-painted old city to Udaipur\'s lakes, Jaisalmer\'s desert landscape and Ranthambore\'s wildlife.',
            'If you are planning your first visit, Jaipur, Udaipur, Jodhpur and Jaisalmer provide a strong introduction to Rajasthan\'s heritage, architecture and landscapes. Travellers with more time can explore destinations such as Pushkar, Ranthambore, Bundi, Chittorgarh, Mount Abu, Bikaner and Mandawa.',
            'The best Rajasthan itinerary is ultimately the one that matches your interests, available time and preferred pace of travel.',
            'Frequently Asked Questions',
            ['type' => 'faq', 'items' => [
                ['q' => 'What are the best places to visit in Rajasthan?', 'a' => 'Some of the most popular destinations include Jaipur, Udaipur, Jodhpur, Jaisalmer, Pushkar, Ranthambore, Bikaner, Mount Abu, Chittorgarh and Bundi.'],
                ['q' => 'Which city is best for a first Rajasthan trip?', 'a' => 'Jaipur is a practical starting point for many first-time visitors because it offers historic forts, palaces, markets and museums and is part of the Delhi-Agra-Jaipur Golden Triangle.'],
                ['q' => 'Which place in Rajasthan is famous for the desert?', 'a' => 'Jaisalmer is one of the main destinations for experiencing the Thar Desert. Visitors can combine the city with desert areas such as Sam for a desert experience.'],
                ['q' => 'Is Udaipur worth visiting?', 'a' => 'Udaipur is known for its lakes, palaces, historic architecture and Aravalli surroundings. Lake Pichola, City Palace and Sajjangarh Monsoon Palace are among its major attractions.'],
                ['q' => 'How many days are enough for Rajasthan?', 'a' => 'A 7-day trip can cover several major destinations, while 10 to 14 days allows you to travel at a more relaxed pace and include additional destinations such as Udaipur, Pushkar, Ranthambore or Bundi.'],
                ['q' => 'What is the best month to visit Rajasthan?', 'a' => 'October through March is generally a comfortable period for sightseeing across much of Rajasthan. However, weather varies by region and winter nights can become quite cold.'],
                ['q' => 'Is Rajasthan suitable for a family trip?', 'a' => 'Yes. Rajasthan offers a wide variety of attractions for families, including forts, palaces, museums, cultural experiences, wildlife destinations and desert activities.'],
                ['q' => 'Which places are best for couples in Rajasthan?', 'a' => 'Udaipur, Jaisalmer, Jaipur and Mount Abu offer different experiences for couples, including lakeside settings, heritage properties, desert landscapes and hill scenery.'],
                ['q' => 'Which places in Rajasthan are good for a wildlife trip?', 'a' => 'Ranthambore is one of the state\'s best-known wildlife destinations and is particularly known for its tiger reserve. Bharatpur is another important destination for birdwatching.'],
                ['q' => 'Is Pushkar worth visiting?', 'a' => 'Pushkar is worth considering if you are interested in temples, pilgrimage sites, local markets and cultural experiences. Pushkar Lake and the Brahma Temple are among its best-known attractions.'],
                ['q' => 'Which is better for a desert experience, Jaisalmer or Bikaner?', 'a' => 'Both offer desert-region experiences, but Jaisalmer is particularly associated with the Thar Desert, its living fort and nearby desert camps. Bikaner offers a different combination of desert heritage, forts, havelis and camel-related attractions.'],
                ['q' => 'Can Rajasthan be covered in one week?', 'a' => 'Yes, but a one-week trip requires selecting a limited number of destinations. Trying to cover every major city in seven days can result in considerable travel time, so it is better to focus on a specific route.'],
                ['q' => 'What should I pack for a Rajasthan trip?', 'a' => 'Pack comfortable walking shoes, lightweight clothing, sun protection and a reusable water bottle. If travelling during winter, carry warm layers because temperatures can drop considerably at night.'],
            ]],
        ],
    ],
];